### ISSUE TITLE
0.9.0 setting expand limit to none makes images too small

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [easymodo/qimgv#210]
If I enable the option "Expand smaller images" in the General Tab of the settings and set the expand limit to none, the images get too small to be viewed and need to be zoomed to be viewable again. Version 0.8.9 worked fine.

I'm using Arch Linux with your PKGBUILD.

**Comment by easymodo** [comment]
yep i messed up somewhere

set it to x4 for now

**Comment by Sebastian-Hirsch** [comment]
I have done that for the time being.

**Comment by nick-s-b** [comment]
After upgrading I noticed the same thing. Setting it from none to x4 fixes it.
Also, the location of qimgv conf file changed. That threw me off since I lost all my keyboard shortcut. Maybe there should be a note or something that greenpepper folder is now not used anymore? Other than that, this update is great!

**Comment by easymodo** [comment]
yeah sorry about the config. if you move it to the new location it will work fine

**Comment by easymodo** [comment]
[v0.9.1](https://github.com/easymodo/qimgv/releases/tag/v0.9.1)
