### ISSUE TITLE
Crash on playing videos (could not initialize OpenGL)

### ISSUE THREAD

**Issue by rwilhelm** [easymodo/qimgv#296]
Hi!

```sh
qimgv any.mp4
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Numeric mode unsupported in the posix collation implementation
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not initialize OpenGL
zsh: abort      qimgv any.mp4
```

So far I can't figure it out. I'm on Gentoo and compiled version 0.9.1 it with the use flags `exif -kde opencv video`.

```
Enabled build options:
    "USE_MPV"
```

Playing anything via mpv on it's own is working fine.

Is there a way to get more debugging out?

Help, please.

**Comment by easymodo** [comment]
Probably something wrong with your qt build..
Does this happen with any other qt video player that uses mpv? For example, you can try [mpc-qt](https://github.com/cmdrkotori/mpc-qt-origin)
I think it embeds mpv in the same way as qimgv

**Comment by ShadowM00n** [comment]
@easymodo I am in the exact same boat as OP, and seeing no further response until now, I'd like to chime in a bit instead, since I was intending on raising this very same issue myself.

There is currently no official ebuild for mpc-qt, so I grabbed the current version from the link you gave, built it, and then simply ran it from where it was compiled for the sake of testing. I was able to play various videos of various file extensions/types with no problems.

I would note that smplayer is also built around Qt, and also uses mpv in what seems to be a similar manner, and I have had no trouble with that program either, so I think it's safe to say that our installation of Qt is behaving correctly.

Given this, I decided to test an observation I had. The current version of mpv in Gentoo is 0.33.1. I noticed that, as it happened, qimgv broke the second-to-last time mpv updated, which was to 0.33.0-r100. The time before that, it was at version 0.32.0-r2. Testing this, I installed both versions, one after the other, running qimgv on the first webm I found on my system afterwards.

As it turns out, qimgv works perfectly fine with mpv 0.32.0-r2, and crashes with versions 0.33.0-r100 and 0.33.1. It seems clear to me, then, that there is some sort of alteration in mpv/libmpv (these ebuilds provide both) between those versions that should be considered.

If I can assist further, please let me know.

**Comment by easymodo** [comment]
wait, you're using the old 0.9.1 release right?

it's probably the [same issue](https://github.com/easymodo/qimgv/issues/259) i've fixed a while ago

please try building qimgv from master

**Comment by ShadowM00n** [comment]
@easymodo That is correct, yes; Gentoo doesn't have an official rolling/git ebuild for qimgv at this point. Either way, I put my mpv version back to 0.33.2, and then built qimgv from master, and this does indeed fix the problem. I suppose we're really just waiting for a new stable release then, so far as that goes on our side. I'm very glad to see that the bug has already been dealt with. Thanks for being so responsive despite this being an accidental repeat.

**Comment by easymodo** [comment]
i guess i'll just hurry up with fixing stuff for 0.9.2 so the fix makes its way into repos
