### ISSUE TITLE
Not opening WEBP files on Gentoo.

### ISSUE THREAD

**Issue by rizzini** [easymodo/qimgv#439]
Any insight on that, guys? It works just fine, except for WEBP files. It opens with a black screen.

**Comment by rizzini** [comment]
Installing dev-qt/qtimageformats package did the trick here. Sorry about the issue.

**Comment by moskalenco-a** [comment]
I have Fedora 39, and this helps(there is qt6-* package installed, but works only after installing qt5 version)

sudo dnf install qt5-qtimageformats

**Comment by HubKing** [comment]
> I have Fedora 39, and this helps(there is qt6-* package installed, but works only after installing qt5 version)
> 
> sudo dnf install qt5-qtimageformats

This should be a bug. At least a bug in the AUR packaging. I installed the AUR version in the screenshot below, and even when I installed its optional dependency, `kimageformats` it did not display WebP. Only after installing `qt5-qtimageformats`, it worked. The package doesn't list `qt5-qtimageformats` even as optional dependencies and it only has `qt6-qtimageformats`. If this app doesn't use qt6-qi... but qt5-qi..., then the dependency should be changed.

![image](https://github.com/easymodo/qimgv/assets/10900489/1110f4ff-c9b6-45e0-8af0-6c17092c6ef2)

![image](https://github.com/easymodo/qimgv/assets/10900489/dc28c517-d9e2-426a-9fb6-b6fca7edd919)


I didn't install "light" version because I wanted that, but because there was no "normal" QT6 version. (either it's QT5 or alpha versions)
